// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.0";

// src/lib/mcp/tools/list-transactions.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_transactions_default = defineTool({
  name: "list_transactions",
  title: "List transactions",
  description: "List the signed-in user's FinTrack+ transactions. Optionally filter by type, project, or date range. Results are scoped to the caller's organization via RLS.",
  inputSchema: {
    type: z.enum(["income", "expense"]).optional().describe("Filter by transaction type."),
    project_id: z.string().uuid().optional().describe("Filter by project ID."),
    from_date: z.string().optional().describe("Inclusive start date (YYYY-MM-DD)."),
    to_date: z.string().optional().describe("Inclusive end date (YYYY-MM-DD)."),
    limit: z.number().int().positive().optional().describe("Max rows to return (default 50, max 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ type, project_id, from_date, to_date, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const cap = Math.min(Math.max(limit ?? 50, 1), 200);
    let q = supabaseForUser(ctx).from("transactions").select("id, type, amount, title, vendor, project_id, handled_by, payment_method, date, time, notes, is_gst").order("date", { ascending: false }).order("time", { ascending: false }).limit(cap);
    if (type) q = q.eq("type", type);
    if (project_id) q = q.eq("project_id", project_id);
    if (from_date) q = q.gte("date", from_date);
    if (to_date) q = q.lte("date", to_date);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { transactions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-transaction.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var create_transaction_default = defineTool2({
  name: "create_transaction",
  title: "Create transaction",
  description: "Create an income or expense entry in FinTrack+ for the signed-in user's organization. Amount is in the org's currency (INR).",
  inputSchema: {
    type: z2.enum(["income", "expense"]).describe("Transaction type."),
    amount: z2.number().positive().describe("Amount, must be positive."),
    vendor: z2.string().min(1).describe("Vendor or payer name."),
    category_id: z2.string().uuid().describe("Category ID (see list_categories)."),
    payment_method: z2.enum(["cash", "online"]).describe("Payment method."),
    date: z2.string().describe("Date in YYYY-MM-DD (local timezone)."),
    time: z2.string().optional().describe("Time in HH:mm (24h). Defaults to now."),
    title: z2.string().optional(),
    project_id: z2.string().uuid().optional(),
    handled_by: z2.string().optional().describe("Partner or company account handle."),
    notes: z2.string().optional(),
    is_gst: z2.boolean().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    const userId = ctx.getUserId();
    const { data: orgId, error: orgErr } = await sb.rpc("get_user_org_id", { _user_id: userId });
    if (orgErr || !orgId) {
      return { content: [{ type: "text", text: "Could not resolve organization for user." }], isError: true };
    }
    const row = {
      type: input.type,
      amount: input.amount,
      vendor: input.vendor,
      category_id: input.category_id,
      payment_method: input.payment_method,
      date: input.date,
      time: input.time ?? (/* @__PURE__ */ new Date()).toTimeString().slice(0, 5),
      title: input.title ?? null,
      project_id: input.project_id ?? null,
      handled_by: input.handled_by ?? null,
      notes: input.notes ?? null,
      is_gst: input.is_gst ?? false,
      user_id: userId,
      org_id: orgId
    };
    const { data, error } = await sb.from("transactions").insert(row).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Created transaction ${data.id}` }],
      structuredContent: { transaction: data }
    };
  }
});

// src/lib/mcp/tools/financial-summary.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var financial_summary_default = defineTool3({
  name: "financial_summary",
  title: "Financial summary",
  description: "Return total income, total expense, and net balance for the caller's organization in an optional date range. Excludes internal transfers by convention (transfers are typically tagged with the vendor 'Internal Transfer', 'Self Transfer', or 'Company Bank Account').",
  inputSchema: {
    from_date: z3.string().optional().describe("Inclusive start date (YYYY-MM-DD)."),
    to_date: z3.string().optional().describe("Inclusive end date (YYYY-MM-DD).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from_date, to_date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser3(ctx).from("transactions").select("type, amount, vendor").range(0, 9999);
    if (from_date) q = q.gte("date", from_date);
    if (to_date) q = q.lte("date", to_date);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const TRANSFER_VENDORS = /* @__PURE__ */ new Set([
      "Internal Transfer",
      "Self Transfer",
      "Company Bank Account"
    ]);
    let income = 0;
    let expense = 0;
    for (const row of data ?? []) {
      if (row.vendor && TRANSFER_VENDORS.has(row.vendor)) continue;
      const amt = Number(row.amount) || 0;
      if (row.type === "income") income += amt;
      else if (row.type === "expense") expense += amt;
    }
    const summary = {
      from_date: from_date ?? null,
      to_date: to_date ?? null,
      income,
      expense,
      balance: income - expense,
      count: data?.length ?? 0
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/list-projects.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z4 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_projects_default = defineTool4({
  name: "list_projects",
  title: "List projects",
  description: "List the caller's organization's projects (events).",
  inputSchema: {
    include_archived: z4.boolean().optional().describe("Include archived projects (default false).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_archived }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser4(ctx).from("projects").select("id, name, description, event_date, start_date, budget_limit, margin, expected_margin, archived, color, created_at").order("created_at", { ascending: false });
    if (!include_archived) q = q.or("archived.is.null,archived.eq.false");
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z5 } from "npm:zod@^4.4.3";
function supabaseForUser5(ctx) {
  return createClient5(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_categories_default = defineTool5({
  name: "list_categories",
  title: "List categories",
  description: "List available income/expense categories for the caller's organization.",
  inputSchema: {
    type: z5.enum(["income", "expense"]).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ type }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser5(ctx).from("categories").select("id, name, icon, color, type").order("name");
    if (type) q = q.eq("type", type);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { categories: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-partners.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.22.0";
function supabaseForUser6(ctx) {
  return createClient6(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_partners_default = defineTool6({
  name: "list_partners",
  title: "List partners & accounts",
  description: "List team partners and company bank accounts. Use their handle (user_id for members, id for company accounts) as `handled_by` on transactions.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser6(ctx).from("partners").select("id, name, color, user_id, role, is_company_account, initial_cash_balance, initial_online_balance");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { partners: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ilgoprsvztbqocbshtoe";
var mcp_default = defineMcp({
  name: "fintrackplus-mcp",
  title: "FinTrack\u207A",
  version: "0.1.0",
  instructions: "Tools to read and manage FinTrack\u207A finances for the signed-in user: list transactions, create income/expense entries, summarize income/expense, and inspect projects, categories, and partners. All data is scoped to the caller's organization via RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_transactions_default,
    create_transaction_default,
    financial_summary_default,
    list_projects_default,
    list_categories_default,
    list_partners_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
